### ISSUE TITLE
Notify user about limitations of 7-zip format for backup purpose on Linux/Unix

### ISSUE THREAD

**Issue by ghost** [gustawho/backupd#1]
Hi, seeing that your project uses 7-zip for backup purposes, it might be nice to inform the user on its limitations, or use tar before compressing with 7z...

Direct quote from http://linux.die.net/man/1/7z:
<quote>
Backup and limitations
DO NOT USE the 7-zip format for backup purpose on Linux/Unix because :
- 7-zip does not store the owner/group of the file.

On Linux/Unix, in order to backup directories you must use tar :
- to backup a directory  : tar cf - directory | 7za a -si directory.tar.7z
- to restore your backup : 7za x -so directory.tar.7z | tar xf -
  </quote>

**Comment by gustawho** [comment]
You're absolutely right. I don't need to preserve ownership myself, so I totally missed that point.

What do you think of _xz_ for better compression and _pigz_ for multi-thread?
`XZ_OPT=-9 tar -Jpcf - /path/to/source | pigz > backup.tar.xz`

**Comment by ghost** [comment]
Easily missed indeed. I got bitten by it recently, that's why I
wanted to point it out here. As to your suggestion using xz/pigz, I
did a few small tests compressing a directory with 'tar Jpcf
- /path/to/source | 7za a -si backup.tar.7z' and 'XZ_OPT=-9 tar -Jpcf -
  /path/to/source | pigz > backup.tar.xz'. Both resulted in a
  similar-sized backup file, but pigz was slightly faster on my system
  (quad-core). Personally I'd go with the xz/pigz combo, as both are
  widely available on most distro's...

All the best with the project :-)

**Comment by gustawho** [comment]
I released the v.0.2 with this changes.

And thank you! I really appreciate your contribution.
